version: '3.8'

services:
  nestjs-app:
    image: nest-deploy-test-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4005:4000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elehdrn1
      POSTGRES_DB: CategoryPrj
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
